/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZOkueBuCYk1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { TopMenu } from "./top-menu"

export function ComponentEngineer() {
  return (
    <div className="h-full flex flex-col space-y-12 md:space-y-16 lg:space-y-20">
      <TopMenu />
      <section id='demestic' className="flex-1 w-full py-12 md:py-24 lg:py-32">
        <div className="container h-full flex flex-col justify-center">
          <div className="space-y-4 md:space-y-6">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">Discover our latest products</h2>
            <p className="text-muted-foreground md:text-lg">Explore our curated selection of high-quality products.</p>
          </div>
          <Carousel className="mt-8 md:mt-12 flex-1">
            <CarouselContent>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Ergonomic Desk Chair</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Upgrade your workspace with our comfortable and stylish desk chair, designed for long hours of
                      productivity.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Wireless Headphones</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Experience immersive audio with our high-quality wireless headphones, perfect for music, movies,
                      and more.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Smart Home Hub</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Elevate your home with our advanced smart home hub, connecting all your devices for seamless
                      control.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Noise-Cancelling Headphones</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Experience uninterrupted audio with our advanced noise-cancelling headphones, perfect for work or
                      play.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Portable Bluetooth Speaker</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Bring your music anywhere with our compact and powerful Bluetooth speaker.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
      <section id='commercial' className="flex-1 w-full py-12 md:py-24 lg:py-32">
        <div className="container h-full flex flex-col justify-center">
          <div className="space-y-4 md:space-y-6">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
              Explore our latest collections
            </h2>
            <p className="text-muted-foreground md:text-lg">
              Discover our curated selection of stylish and functional products.
            </p>
          </div>
          <Carousel className="mt-8 md:mt-12 flex-1">
            <CarouselContent>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Modern Minimalist Lamp</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Elevate your space with our sleek and energy-efficient minimalist lamp, perfect for any room.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Sustainable Water Bottle</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Stay hydrated in style with our eco-friendly and reusable water bottle, perfect for on-the-go.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
              <CarouselItem>
                <div className="grid md:grid-cols-2 gap-6 md:gap-8 h-full">
                  <img
                    src="/placeholder.svg"
                    width={800}
                    height={450}
                    alt="Product Image"
                    className="aspect-video rounded-lg object-cover h-full"
                  />
                  <div className="space-y-4 md:space-y-6 h-full flex flex-col justify-center">
                    <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">Sleek Desk Organizer</h3>
                    <p className="text-muted-foreground md:text-lg">
                      Keep your workspace tidy and organized with our stylish and functional desk organizer.
                    </p>
                    <div className="flex items-center gap-4">
                      <Button size="lg">Shop Now</Button>
                      <Link href="#" className="text-primary hover:underline" prefetch={false}>
                        Learn More
                      </Link>
                    </div>
                  </div>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
    </div>
  )
}
