/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/539yv8fkoQD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { TopMenu } from "./top-menu";
import { VideoPlayComponent } from "./video-play-component";

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function ComponentProduct() {
  return (
    <div className="w-full">
      <TopMenu />
      <section id="u-solar-i3" className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Solar Power System
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Solar Power System
              </p>
            </div>
          </div>
          <div className="space-y-4">
            <VideoPlayComponent />
          </div>
        </div>
      </section>
      <section id='u-solar-domestic' className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Scalable and Secure</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our product is designed to scale with your business, and we take security seriously to protect your
                data.
              </p>
            </div>
          </div>
          <div className="space-y-4">
            <VideoPlayComponent />
          </div>
        </div>
      </section>
      <section id='u-solar-rv' className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Construction-Window & Door
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our product seamlessly integrates with your existing tools and workflows, making it easy to get started
                and see immediate benefits.
              </p>
            </div>
          </div>
          <div className="space-y-4">
            <VideoPlayComponent />
          </div>
        </div>
      </section>
      <section id='u-solar-ai-in-one' className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Energy Saving Paint
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our dedicated support team is here to help you every step of the way, ensuring you get the most out of
                our product.
              </p>
            </div>
          </div>
          <div className="space-y-4">
            <VideoPlayComponent />
          </div>
        </div>
      </section>
      <section id='u-solar-renew' className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid gap-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                CCTV
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our product is used by thousands of businesses across a variety of industries, helping them streamline
                their operations and achieve their goals.
              </p>
            </div>
          </div>
          <div className="space-y-4">
            <VideoPlayComponent />
          </div>
        </div>
      </section>
    </div>
  )
}
