/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UluZ19tLjSj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@radix-ui/react-label"
import { Button } from "./ui/button"
import { Input } from "./ui/input"
import { Textarea } from "./ui/textarea"
import { ShopModal } from "./shop-modal"
import { FacebookFooter } from "./facebook-footer"
import { WhatsAppButton } from "./whats-app-button"
import { VideoPlayComponent } from "./video-play-component"

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <div className="bg-[#4c51bf] text-white py-2 text-center text-sm font-medium">
        Enjoy standard shipping on all orders
      </div>
      <header className="px-4 lg:px-6 h-14 flex items-center bg-gradient-to-r from-[#4c51bf] to-[#6b46c1] text-white">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6 text-white" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            About Us
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            Product & Service
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            Solar Power System
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            Construction-Window & Door
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            Energy Saving Paint
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            EV Retrofit Battery
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            CCTV
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            MIC Construction
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4 text-white" prefetch={false}>
            Contact Us
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-[#4c51bf] to-[#6b46c1] text-white relative">
          <div className="absolute inset-0 bg-[url('/hero-background.jpg')] bg-cover bg-center opacity-20" />
          <div className="container px-4 md:px-6 relative z-10">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-12 xl:gap-16">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2 text-center lg:text-left">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    New Zealand U-solar & Technology Company Limited
                  </h1>
                  <p className="max-w-[600px] text-white md:text-xl">
                    Acme Inc provides innovative solutions to help your business thrive. From cloud-based infrastructure
                    to cutting-edge analytics, we have the tools to take your company to the next level.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center lg:justify-start">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#7b46c1] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#6b46c1] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Get Started
                  </Link>
                  {/* Learn More */}
                  <ShopModal />
                </div>
              </div>
              <video
                src="/hero-video.mp4"
                autoPlay
                loop
                muted
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f3f4f6]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#e5e7eb] px-3 py-1 text-sm text-[#4b5563]">
                  Key Features
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#1f2937]">
                  Unlock Your Business Potential
                </h2>
                <p className="max-w-[900px] text-[#4b5563] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Acme Inc offers a comprehensive suite of tools and services to help your business thrive. From
                  cloud-based infrastructure to advanced analytics, we have everything you need to take your company to
                  the next level.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-[#1f2937]">Cloud Infrastructure</h3>
                      <p className="text-[#4b5563]">
                        Scalable and reliable cloud-based infrastructure to power your business.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-[#1f2937]">Advanced Analytics</h3>
                      <p className="text-[#4b5563]">
                        Gain deep insights into your business with our powerful analytics tools.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-[#1f2937]">Automation</h3>
                      <p className="text-[#4b5563]">Streamline your workflows with our suite of automation tools.</p>
                    </div>
                  </li>
                </ul>
              </div>
              <video
                src="/features-video.mp4"
                autoPlay
                loop
                muted
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <VideoPlayComponent />
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <VideoPlayComponent />
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-[#1f2937]">
                Take Your Business to New Heights
              </h2>
              <p className="mx-auto max-w-[600px] text-[#4b5563] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Let Acme Inc be your partner in growth. Contact us today to learn how we can help your business thrive.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#4c51bf] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#6b46c1] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Get Started
              </Link>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md border border-[#4c51bf] bg-transparent px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#6b46c1] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Contact Sales
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f3f4f6]">
          <div className="container px-4 md:px-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#1f2937]">About Acme Inc</h2>
                  <p className="max-w-[600px] text-[#4b5563] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Acme Inc was founded in 2010 with the mission to provide innovative solutions to help businesses
                    thrive. Our team of experts is dedicated to delivering cutting-edge technology and personalized
                    service to our clients.
                  </p>
                </div>
                <Carousel className="w-full max-w-md">
                  <CarouselContent>
                    <CarouselItem>
                      <div className="flex items-center gap-4">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>EC</AvatarFallback>
                        </Avatar>
                        <div>
                          <h3 className="text-xl font-bold text-[#1f2937]">Eric C. Tam, CEO</h3>
                          <p className="text-[#4b5563]">
                            Eric has over 15 years of experience in the technology industry and is passionate about
                            helping businesses succeed.
                          </p>
                        </div>
                      </div>
                    </CarouselItem>
                    <CarouselItem>
                      <div className="flex items-center gap-4">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <h3 className="text-xl font-bold text-[#1f2937]">Jane Doe, CTO</h3>
                          <p className="text-[#4b5563]">
                            Jane has over 10 years of experience in software engineering and is passionate about
                            building innovative solutions.
                          </p>
                        </div>
                      </div>
                    </CarouselItem>
                    <CarouselItem>
                      <div className="flex items-center gap-4">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JB</AvatarFallback>
                        </Avatar>
                        <div>
                          <h3 className="text-xl font-bold text-[#1f2937]">John Bravo, VP of Sales</h3>
                          <p className="text-[#4b5563]">
                            John has over 8 years of experience in sales and is dedicated to helping our clients
                            succeed.
                          </p>
                        </div>
                      </div>
                    </CarouselItem>
                  </CarouselContent>
                  <CarouselPrevious />
                  <CarouselNext />
                </Carousel>
              </div>
              <Carousel className="w-full max-w-md">
                <CarouselContent>
                  <CarouselItem>
                    <video
                      src="/about-video-1.mp4"
                      autoPlay
                      loop
                      muted
                      className="aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                    />
                  </CarouselItem>
                  <CarouselItem>
                    <video
                      src="/about-video-2.mp4"
                      autoPlay
                      loop
                      muted
                      className="aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                    />
                  </CarouselItem>
                  <CarouselItem>
                    <video
                      src="/about-video-3.mp4"
                      autoPlay
                      loop
                      muted
                      className="aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                    />
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f3f4f6]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#1f2937]">Contact Us</h2>
                <p className="max-w-[600px] text-[#4b5563] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Have a question or need help? Fill out the form below and we'll get back to you as soon as possible.
                </p>
              </div>
              <form className="w-full max-w-md space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" type="text" placeholder="Enter your name" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Enter your email" required />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Enter your message" className="min-h-[100px]" required />
                </div>
                <Button type="submit" className="w-full">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </section>
        <WhatsAppButton />
      </main>
      {/* <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0" /> */}
      <FacebookFooter />
    </div>
  )
}

// @ts-ignore
function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}

// @ts-ignore
function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
